#!/usr/bin/env bash

TEXT="Duckduckgo\nReddit\nGithub\nUncyclopedia"

DMENU="$( echo -e $TEXT | dmenu -l 4 -p web )"

BROWSER="/usr/bin/chromium" #Change this to your preference

case "$DMENU" in
	Duckduckgo)   $BROWSER https://duckduckgo.com       ;;
	Reddit)       $BROWSER https://reddit.com           ;;
	Github)       $BROWSER https://github.com           ;;
	Uncyclopedia) $BROWSER uncyclopedia.wikia.com       ;;
esac

